# Generated by Django 4.2 on 2026-01-18 05:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_mastercrop"),
        ("farmer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crop",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Crop Listing",
                "verbose_name_plural": "Crop Listings",
            },
        ),
        migrations.RemoveField(
            model_name="crop",
            name="crop_name",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="crop_type",
        ),
        migrations.AddField(
            model_name="crop",
            name="master_crop",
            field=models.ForeignKey(
                blank=True,
                help_text="Select crop type from admin's master list",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listings",
                to="admin_panel.mastercrop",
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="availability_date",
            field=models.DateField(help_text="When is it available for sale/pickup?"),
        ),
        migrations.AlterField(
            model_name="crop",
            name="crop_image",
            field=models.ImageField(
                blank=True,
                help_text="Photo of YOUR actual crop (optional)",
                null=True,
                upload_to="crops/",
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Additional details about your specific crop listing",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="harvest_date",
            field=models.DateField(help_text="When was this crop harvested?"),
        ),
        migrations.AlterField(
            model_name="crop",
            name="location",
            field=models.CharField(help_text="Farm/pickup location", max_length=255),
        ),
        migrations.AlterField(
            model_name="crop",
            name="price_per_unit",
            field=models.FloatField(
                help_text="Price per unit",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="quality_grade",
            field=models.CharField(
                choices=[
                    ("A", "Grade A - Premium"),
                    ("B", "Grade B - Standard"),
                    ("C", "Grade C - Basic"),
                ],
                default="B",
                help_text="Quality grade of your crop",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="quantity",
            field=models.FloatField(
                help_text="Available quantity",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilograms"),
                    ("tons", "Tons"),
                    ("quintals", "Quintals"),
                    ("pieces", "Pieces"),
                ],
                default="kg",
                max_length=20,
            ),
        ),
    ]
