# Generated by Django 4.2 on 2026-01-29 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_mastercrop_allow_detection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farmer", "0002_alter_crop_options_remove_crop_crop_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cropdisease",
            name="farmer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disease_detections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cropdisease",
            name="master_crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="master_diseases",
                to="admin_panel.mastercrop",
            ),
        ),
        migrations.AlterField(
            model_name="cropdisease",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diseases",
                to="farmer.crop",
            ),
        ),
        migrations.AlterField(
            model_name="cropdisease",
            name="disease_type",
            field=models.CharField(
                choices=[
                    ("fungal", "Fungal Disease"),
                    ("bacterial", "Bacterial Disease"),
                    ("viral", "Viral Disease"),
                    ("pest", "Pest Damage"),
                    ("healthy", "Healthy"),
                ],
                max_length=20,
            ),
        ),
    ]
