# Generated by Django 4.2.28 on 2026-03-07 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0003_cropdisease_farmer_cropdisease_master_crop_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropPriceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("market", models.CharField(max_length=60)),
                ("commodity", models.CharField(max_length=60)),
                ("variety", models.CharField(max_length=80)),
                ("price_per_kg", models.FloatField()),
                ("avg_temp_c", models.FloatField()),
                ("max_temp_c", models.FloatField()),
                ("min_temp_c", models.FloatField()),
                ("rainfall_mm", models.FloatField()),
                ("cumulative_rainfall_mm", models.FloatField()),
                ("flood", models.IntegerField(default=0)),
                ("drought", models.IntegerField(default=0)),
                ("yield_per_hectare", models.FloatField()),
                ("production_tonnes", models.FloatField()),
                ("area_hectares", models.FloatField()),
                ("import_tonnes", models.FloatField()),
                ("export_tonnes", models.FloatField()),
                ("fertilizer_cost", models.FloatField()),
                ("seed_cost", models.FloatField()),
                ("labor_cost", models.FloatField()),
                ("fuel_cost", models.FloatField()),
                ("inflation", models.FloatField()),
                ("cpi", models.FloatField()),
                ("lag1_price", models.FloatField()),
                ("lag2_price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Crop Price Data",
                "verbose_name_plural": "Crop Price Data",
                "ordering": ["year", "month", "market", "commodity", "variety"],
                "unique_together": {
                    ("year", "month", "market", "commodity", "variety")
                },
            },
        ),
        migrations.DeleteModel(
            name="CropPrice",
        ),
    ]
