# Generated by Django 6.0.3 on 2026-03-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_crop_price_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='out_of_stock_since',
            field=models.DateTimeField(blank=True, help_text='When crop went out of stock (auto-deletes after 24h)', null=True),
        ),
    ]
