# Generated by Django 4.2.29 on 2026-04-02 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_irrigation_record_user(apps, schema_editor):
    IrrigationRecord = apps.get_model("farmer", "IrrigationRecord")

    for record in IrrigationRecord.objects.filter(user__isnull=True).select_related("crop"):
        crop = getattr(record, "crop", None)
        if crop and getattr(crop, "farmer_id", None):
            IrrigationRecord.objects.filter(pk=record.pk, user__isnull=True).update(user_id=crop.farmer_id)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farmer", "0008_update_irrigation_method_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="irrigationrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="irrigation_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(populate_irrigation_record_user, migrations.RunPython.noop),
    ]
