# Generated by Django 4.2.29 on 2026-04-02 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0009_irrigationrecord_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irrigationrecord",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="irrigation_records",
                to="farmer.irrigationcrop",
            ),
        ),
    ]
