# Generated by Django 4.2.29 on 2026-04-02 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0010_alter_irrigationrecord_crop"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="area_size",
            field=models.FloatField(
                default=1.0,
                help_text="Field size used for irrigation planning",
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="area_unit",
            field=models.CharField(
                choices=[("m2", "m²"), ("acre", "Acre"), ("hectare", "Hectare")],
                default="m2",
                help_text="Unit of the field size (m², acre, hectare)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="irrigationcrop",
            name="area_size",
            field=models.FloatField(
                default=1.0, validators=[django.core.validators.MinValueValidator(0.01)]
            ),
        ),
        migrations.AddField(
            model_name="irrigationcrop",
            name="area_unit",
            field=models.CharField(
                choices=[("m2", "m²"), ("acre", "Acre"), ("hectare", "Hectare")],
                default="m2",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="irrigationcrop",
            name="moisture_threshold",
            field=models.PositiveSmallIntegerField(
                default=45,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="irrigationcrop",
            name="retention_factor",
            field=models.FloatField(
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
        migrations.AddField(
            model_name="irrigationcrop",
            name="water_per_m2",
            field=models.FloatField(
                default=2.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="irrigationcropcatalog",
            name="moisture_threshold",
            field=models.PositiveSmallIntegerField(
                default=45,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="irrigationcropcatalog",
            name="retention_factor",
            field=models.FloatField(
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
        migrations.AddField(
            model_name="irrigationcropcatalog",
            name="water_per_m2",
            field=models.FloatField(
                default=2.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
