# Generated by Django 4.2 on 2026-02-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auth_type",
            field=models.CharField(
                choices=[("pin", "PIN"), ("password", "Password")],
                default="password",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(default="Bangladesh", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pin_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="preferences",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="upazila",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
