# Generated by Django 4.2.28 on 2026-03-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_otpverification_passwordresettoken_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("farmer", "Farmer"),
                    ("buyer", "Buyer"),
                    ("admin", "Admin"),
                    ("pending", "Pending"),
                ],
                default="buyer",
                max_length=10,
            ),
        ),
    ]
