# Generated by Django 4.2 on 2026-02-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_email_verified_customuser_phone_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailPhoneVerification',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_verified',
        ),
    ]
