# Generated by Django 6.0.3 on 2026-03-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role'),
        ('users', '0004_delete_emailphoneverification_and_more'),
    ]

    operations = [
    ]
