# Generated by Django 6.0.3 on 2026-03-08 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20260308_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='total_spent',
            field=models.FloatField(default=0, help_text='Total amount spent on confirmed orders', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
