# Generated by Django 6.0.3 on 2026-03-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_buyerprofile_total_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('pending', 'Pending')], default='buyer', max_length=10),
        ),
    ]
