# Generated by Django 6.0.3 on 2026-04-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_farmer_nid_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmerprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
