# Generated by Django 6.0.3 on 2026-04-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_farmerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmerprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='nid_card_image',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='nid_number',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='resubmit_requested_at',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='resubmit_requested_reason',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('not_submitted', 'Not Submitted')], default='not_submitted', max_length=20),
        ),
    ]
