# Generated by Django 6.0.3 on 2026-04-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_farmerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_date',
            field=models.DateTimeField(blank=True, help_text='When user was blocked', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blocked_reason',
            field=models.TextField(blank=True, help_text='Reason for blocking', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_blocked_by_admin',
            field=models.BooleanField(default=False, help_text='User blocked by admin'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
