# Generated by Django 6.0.3 on 2026-04-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_farmersettings_farmerpaymentmethod'),
    ]

    operations = [
    ]
