# Generated by Django 4.2.29 on 2026-04-21 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_set_two_factor_default'),
        ('users', '0014_ensure_block_columns_exist'),
    ]

    operations = [
    ]
