# Generated by Django 4.2.29 on 2026-04-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20260421_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='nid_admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes on NID verification', null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='nid_approval_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', help_text='NID verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='nid_approved_date',
            field=models.DateTimeField(blank=True, help_text='When NID was approved by admin', null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='nid_number',
            field=models.CharField(blank=True, help_text='National ID Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='nid_photo',
            field=models.ImageField(blank=True, help_text='NID Photo/Document', null=True, upload_to='nid_photos/'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='nid_submission_date',
            field=models.DateTimeField(blank=True, help_text='When NID was submitted', null=True),
        ),
    ]
