# Generated by Django 4.2 on 2026-01-18 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop_name",
                    models.CharField(
                        help_text="Name of the crop (e.g., Tomato, Rice)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "crop_type",
                    models.CharField(
                        choices=[
                            ("organic", "Organic"),
                            ("conventional", "Conventional"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="conventional",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vegetables", "Vegetables"),
                            ("fruits", "Fruits"),
                            ("grains", "Grains"),
                            ("pulses", "Pulses"),
                            ("spices", "Spices"),
                            ("cash_crops", "Cash Crops"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="General description of this crop",
                        null=True,
                    ),
                ),
                (
                    "generic_image",
                    models.ImageField(
                        blank=True,
                        help_text="Generic crop image",
                        null=True,
                        upload_to="master_crops/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this crop available for farmers to list?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_master_crops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Crop Template",
                "verbose_name_plural": "Master Crop Templates",
                "ordering": ["crop_name"],
            },
        ),
    ]
