# Generated by Django 4.2 on 2026-01-18 05:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_panel", "0002_mastercrop"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.1)]
                    ),
                ),
                ("unit", models.CharField(default="kg", max_length=20)),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("location", models.CharField(max_length=255)),
                ("harvest_date", models.DateField()),
                ("availability_date", models.DateField()),
                (
                    "quality_grade",
                    models.CharField(
                        choices=[
                            ("grade_a", "Grade A (Excellent)"),
                            ("grade_b", "Grade B (Good)"),
                            ("grade_c", "Grade C (Standard)"),
                        ],
                        default="grade_b",
                        max_length=20,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "specific_description",
                    models.TextField(
                        blank=True,
                        help_text="Details about THIS specific batch",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_listings",
                        to="admin_panel.mastercrop",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
