# Generated by Django 4.2 on 2026-01-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_farmerlisting"),
    ]

    operations = [
        migrations.AddField(
            model_name="mastercrop",
            name="allow_detection",
            field=models.BooleanField(
                default=True,
                help_text="Allow farmers to run AI disease detection on this crop type",
            ),
        ),
    ]
