# Generated by Django 6.0.3 on 2026-03-26 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_userreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userapproval',
            name='assigned_moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buyer_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userapproval',
            name='inspection_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userapproval',
            name='inspection_status',
            field=models.CharField(choices=[('pending_assignment', 'Pending Moderator Assignment'), ('assigned', 'Moderator Assigned'), ('photos_submitted', 'Photos Submitted')], default='pending_assignment', max_length=30),
        ),
        migrations.AddField(
            model_name='userapproval',
            name='inspection_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BuyerInspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='buyer_inspections/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_photos', to='admin_panel.userapproval')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_inspection_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
