# Generated by Django 6.0.3 on 2026-04-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_fix_legacy_inspection_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapproval',
            name='nid_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to='approvals/nid/'),
        ),
        migrations.AddField(
            model_name='userapproval',
            name='nid_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
