# Generated by Django 6.0.3 on 2026-04-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_userapproval_nid_card_photo_userapproval_nid_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapproval',
            name='nid_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
