# Generated by Django 6.0.3 on 2026-04-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_remove_nid_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapproval',
            name='nid_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
