# Generated by Django 6.0.3 on 2026-04-14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_userapproval_nid_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AgriGenie', max_length=120)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla'), ('hi', 'Hindi')], default='en', max_length=10)),
                ('default_timezone', models.CharField(choices=[('Asia/Dhaka', 'Asia/Dhaka (UTC+6)'), ('Asia/Kolkata', 'Asia/Kolkata (UTC+5:30)'), ('UTC', 'UTC'), ('Europe/London', 'Europe/London'), ('America/New_York', 'America/New_York')], default='Asia/Dhaka', max_length=64)),
                ('auto_approve_new_users', models.BooleanField(default=False)),
                ('allow_admin_role', models.BooleanField(default=True)),
                ('allow_user_role', models.BooleanField(default=True)),
                ('allow_moderator_role', models.BooleanField(default=True)),
                ('max_users_limit', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('default_new_user_role', models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=20)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('system_alert_notifications_enabled', models.BooleanField(default=True)),
                ('alert_threshold_percent', models.PositiveSmallIntegerField(default=85, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password_min_length', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(64)])),
                ('require_password_uppercase', models.BooleanField(default=True)),
                ('require_password_lowercase', models.BooleanField(default=True)),
                ('require_password_numbers', models.BooleanField(default=True)),
                ('enable_two_factor_auth', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.PositiveSmallIntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (60, '1 hour'), (120, '2 hours'), (240, '4 hours')], default=30)),
                ('max_login_attempts', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('enable_ai_recommendations', models.BooleanField(default=True)),
                ('ai_model_version', models.CharField(choices=[('v1', 'v1 Stable'), ('v2', 'v2 Enhanced'), ('v3-beta', 'v3 Beta')], default='v1', max_length=20)),
                ('ai_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('enable_disease_detection', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Settings',
                'verbose_name_plural': 'Admin Settings',
            },
        ),
    ]
