# Generated by Django 4.2.29 on 2026-04-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0012_adminsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("update_profile", "Update Profile"),
                    ("toggle_2fa", "Toggle Two-Factor Authentication"),
                    ("security_logout", "Logout All Sessions"),
                    ("create_crop", "Create Crop"),
                    ("update_crop", "Update Crop"),
                    ("delete_crop", "Delete Crop"),
                    ("remove_crop", "Remove Crop"),
                    ("approve_user", "Approve User"),
                    ("reject_user", "Reject User"),
                    ("place_order", "Place Order"),
                    ("cancel_order", "Cancel Order"),
                    ("upload_image", "Upload Image"),
                    ("send_message", "Send Message"),
                ],
                max_length=50,
            ),
        ),
    ]
